export const GET_PARKINGS_BY_CITY = 'GET_PARKINGS_BY_CITY';
export const GET_SINGLE_PARKING = 'GET_SINGLE_PARKING';
export const SET_PARKINGS = 'SET_PARKINGS';
export const CREATE_PARKING = 'CREATE_PARKING';
export const UPDATE_PARKING = 'UPDATE_PARKING';
export const DELETE_PARKING = 'DELETE_PARKING';
export const SEARCH_CITY = 'SEARCH_CITY';
export const BOOKING_PARKING = 'BOOKING_PARKING';
